### PR TITLE
Note problematic setup query

### PR DESCRIPTION
**Pull request by matkoniecz**
(BTW, I have not yet figured out whether I am supposed to install phpmyadmin within container or on host system)

### CODE REVIEW

**Comment by westnordost** [comment]
So you can reproduce that right?

**Comment by westnordost** [comment]
I used to test this with a XAMPP, phpmyadmin was preinstalled.

**Comment by matkoniecz** [comment]
No, I just assumed that it is true.

I also tried to get ability to run database commands, but I am doing something wrong

```
vscode ➜ /etc/init.d $ mysql statistics
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)
vscode ➜ /etc/init.d $ cat /run/mysqld/mysqld.soc
cat: /run/mysqld/mysqld.soc: No such file or directory
```

**Comment by westnordost** [comment]
Hm sorry, this is not my project setup, cannot help here. My project setup was an old-fashioned XAMPP with `htdocs/` directory in which I just put all the PHP scripts and edited them directly with notepad++ in that directory, no IDE used.

**Comment by matkoniecz** [comment]
Oh right, I will try once again without devcontainer relying on a a proprietary software and I will try describing how one can do this.

I got stuck with devcontainer because it was described in the readme as a proper way to do this.

I will also retest problem mentioned here.

**Comment by matkoniecz** [comment]
better instructions now live in https://github.com/matkoniecz/fresh_database

I plan to open PR to include something like this within this repo (to save time for other and maybe future me)

**Pull request closed without merging**
